### ISSUE TITLE
error when using the upload function

### ISSUE THREAD

**Issue by luislizcano** [samapriya/geeup#23]
Hi, I have been trying to upload images to my GEE Assets using the upload function of geeup, but it seems it is not working.

This is the error:

`Traceback (most recent call last):
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "c:\users\\anaconda3\envs\ee\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\\anaconda3\envs\ee\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "c:\users\\anaconda3\envs\ee\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\\anaconda3\envs\ee\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\\anaconda3\envs\ee\Scripts\geeup.exe\__main__.py", line 7, in <module>
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\geeup\geeup.py", line 267, in main
    func(args)
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\geeup\geeup.py", line 176, in upload_from_parser
    upload(user=args.user,
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\geeup\batch_uploader.py", line 99, in upload
    google_session = __get_google_auth_session(user, password)
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\geeup\batch_uploader.py", line 309, in __get_google_auth_session
    driver = Firefox(
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "c:\users\\anaconda3\envs\ee\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver.exe' executable needs to be in PATH.`

I have working in a virtual environment exlcusive for GEE, have autheticated my google credentials, geeup, selenium, geckodriver and  and webdriver-manager are updated.

THanks

Luis

**Comment by samapriya** [comment]
Can you check the path of the geeup.py file and the geckodriver.exe file as downloaded on to your system? Make sure that 

```
geeup init
```

is indeed downloading your geckodriver.exe file to the same folder.

**Comment by samapriya** [comment]
Closing this issue since I have had no response since the last update. Feel free to reopen
