### ISSUE TITLE
NameError: name 'robot_account' is not defined

### ISSUE THREAD

**Issue by initze** [samapriya/geeup#29]
Hi Samapriya,
while testing geeup I ran into 

> NameError: name 'robot_account' is not defined

full output below

geeup seemingly tries to upload but runs into the error eventually.
metadata file is in the parent dir. tif files are in tiles subdir
The ImageCollection is created successfully

Thanks in advance for your help

Here is my setup:
```
geeup 0.4.4
Windows 10
conda environment (python 3.7.6)
```

`(gee) C:\Users\initze\geeup>geeup upload --source K:\42_MACS_Processing\Ikpikpuk_S\Ikpikpuk_S_pix4d\upload_test\files --dest users/ingmarnitze/MACS_DEM --metadata K:\42_MACS_Processing\Ikpikpuk_S\Ikpikpuk_S_pix4d\upload_test\meta.csv --user MYACCOUNT --nodata 0
`

> Collection users/ingmarnitze/MACS_DEM already exists
Processing image 1 out of 2: K:\42_MACS_Processing\Ikpikpuk_S\Ikpikpuk_S_pix4d\upload_test\files\Ikpikpuk_S_pix4d_dsm_1_1.tif
Traceback (most recent call last):
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\Scripts\earthengine-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\eecli.py", line 102, in main
    _run_command()
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\eecli.py", line 67, in _run_command
    args.project_override
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\utils.py", line 72, in __init__
    self._robot_account = robot_account
NameError: name 'robot_account' is not defined
Processing image 2 out of 2: K:\42_MACS_Processing\Ikpikpuk_S\Ikpikpuk_S_pix4d\upload_test\files\Ikpikpuk_S_pix4d_dsm_1_2.tif
Traceback (most recent call last):
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\Scripts\earthengine-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\eecli.py", line 102, in main
    _run_command()
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\eecli.py", line 67, in _run_command
    args.project_override
  File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\gee\lib\site-packages\ee\cli\utils.py", line 72, in __init__
    self._robot_account = robot_account
NameError: name 'robot_account' is not defined

**Comment by initze** [comment]
updating earthengine-api from 0.1.231 to 0.1.238 fixed the issue

**Comment by samapriya** [comment]
Thank you @initze 
and apologies for the delay will update this in the requirements to avoid any issues for the next release
