### ISSUE TITLE
Permission denied anywhere I want to write the metadata

### ISSUE THREAD

**Issue by adwiputra** [samapriya/geeup#33]
Hi,

I encountered an error when running the getmeta function. The error message says:
```
Traceback (most recent call last):
  File "c:\users\adrian dwiputra\.conda\envs\ee\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\adrian dwiputra\.conda\envs\ee\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ADRIAN DWIPUTRA\.conda\envs\ee\Scripts\geeup.exe\__main__.py", line 7, in <module>
  File "c:\users\adrian dwiputra\.conda\envs\ee\lib\site-packages\geeup\geeup.py", line 312, in main
    func(args)
  File "c:\users\adrian dwiputra\.conda\envs\ee\lib\site-packages\geeup\geeup.py", line 197, in getmeta_from_parser
    getmeta(indir=args.input,mfile=args.metadata)
  File "c:\users\adrian dwiputra\.conda\envs\ee\lib\site-packages\geeup\getmeta.py", line 14, in getmeta
    with open(mfile,'w') as csvfile:
PermissionError: [Errno 13] Permission denied: 'E:\\metadataS2'
```
I am running the geeup on windows 10 using the Anaconda Prompt with administrator access. I have tried turning off all of the antivirus activities that may prevent access, but still no luck. Can you provide any clue that may help to troubleshoot this issue?

Thanks so much for such a useful package, as well as your kind help!

**Comment by samapriya** [comment]
So this might be an easy fix getmeta function writes a CSV file
```
geeup getmeta --input "Folder Path to where your .tif files are located" --metadata "Full path to a metadata.csv"
```

so in this case a setup could be 

```
geeup getmeta --input "E:\source_imagery" --metadata "E:\source_metadata.csv"
```

Make sure the **--metadata path ends with a .csv** since you are writing a CSV file. Let me know if this fixes your issue I am closing this issue feel free to reopen if there are remaining issues
