### ISSUE TITLE
geeup doesn't build correctly on conda

### ISSUE THREAD

**Issue by spittssj** [samapriya/geeup#34]
I'm starting to work with GEE for my research and am grateful to find geeup. I use conda to manage my GIS environment because it also contains PostgreSQL. 

I tried to build geeup using `conda skeleton pip` and I got the following error below. It has to do with the `setup.py`. Here is a short reproducible example:

```
(comonsit) stephenpitts@Ellacuria python-packaging % python
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) 
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.version import StrictVersion
>>> StrictVersion("'49.6.0.post20210108")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stephenpitts/miniconda3/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/Users/stephenpitts/miniconda3/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number ''49.6.0.post20210108'
>>> 
```
I don't know if the call to `StrictVersion` in `setup.py` is automatically generated or if that is something you could change.  Here is the full output from `conda skeleton pypi geeup`. 
 
```
PyPI URL:  https://files.pythonhosted.org/packages/3b/55/f9b058600df0d01001e2288a5509c4c9dcaa83cd0c45c5b2be44bcbab80a/geeup-0.4.6.tar.gz
Unpacking geeup...
done
working in /var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpkxiuq4s9conda_skeleton_geeup-0.4.6.tar.gz
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.12.5-h033912b_0     conda-forge
    certifi:         2020.12.5-py39h6e9494a_1 conda-forge
    libcxx:          11.1.0-habf9029_0        conda-forge
    libffi:          3.3-h046ec9c_2           conda-forge
    ncurses:         6.2-h2e338ed_4           conda-forge
    openssl:         1.1.1k-h0d85af4_0        conda-forge
    patch:           2.7.6-hbcf498f_1002      conda-forge
    pip:             21.1-pyhd8ed1ab_0        conda-forge
    python:          3.9.2-h2502468_0_cpython conda-forge
    python_abi:      3.9-1_cp39               conda-forge
    pyyaml:          5.4.1-py39hcbf5805_0     conda-forge
    readline:        8.1-h05e3726_0           conda-forge
    setuptools:      49.6.0-py39h6e9494a_3    conda-forge
    sqlite:          3.35.5-h44b9ce1_0        conda-forge
    tk:              8.6.10-h0419947_1        conda-forge
    tzdata:          2021a-he74cb21_0         conda-forge
    wheel:           0.36.2-pyhd3deb0d_0      conda-forge
    xz:              5.2.5-haf1e3a3_1         conda-forge
    yaml:            0.2.5-haf1e3a3_0         conda-forge
    zlib:            1.2.11-h7795811_1010     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Applying patch: /var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpkxiuq4s9conda_skeleton_geeup-0.4.6.tar.gz/pypi-distutils.patch
Applying patch: /var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpkxiuq4s9conda_skeleton_geeup-0.4.6.tar.gz/pypi-distutils.patch with args:
['-Np0', '-i', '/var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpv7ma5rte/pypi-distutils.patch.native', '--binary']
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
Traceback (most recent call last):
  File "/private/var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpkxiuq4s9conda_skeleton_geeup-0.4.6.tar.gz/geeup-0.4.6/setup.py", line 10, in <module>
    if StrictVersion(setuptools_version) < StrictVersion("38.3.0"):
  File "/Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '49.6.0.post20210108'
$PYTHONPATH = /var/folders/x6/h7khltjs35s663pvw6lskbv00000gn/T/tmpkxiuq4s9conda_skeleton_geeup-0.4.6.tar.gz/geeup-0.4.6:/Users/stephenpitts/miniconda3/envs/comonsit/share/qgis/python/plugins:/Users/stephenpitts/miniconda3/envs/comonsit/share/qgis/python:

Leaving build/test directories:
  Work:
 /Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/work 
  Test:
 /Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/test_tmp 
Leaving build/test environments:
  Test:
source activate  /Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold 
  Build:
source activate  /Users/stephenpitts/miniconda3/conda-bld/skeleton_1619622828107/_build_env 
```

**Comment by samapriya** [comment]
Removed StrictVersion in setup.py for version 0.4.7, let me know if that solves the issue

**Comment by spittssj** [comment]
Your change solved that issue, so I could create the conda skeleton for `geeup`.

I needed three other tweaks before conda finally packaged `geeup`:
1) I also had to manually package pySmartDL. The version on conda-forge is 7 years old: https://anaconda.org/auto/pysmartdl
2) I had to manually edit the `meta.yaml` because conda packages have dashes and not underscores (earthengine-api and requests-toolbox)
3) For now I eliminated the dependency on pipwin (because I'm on a MacOS X)

With these it successfully downloaded and installed. Now I'm having some Selenium troubleshooting issues (probably because my GEE access is through my University Google account, which has a different type of authentication).

Once the semester ends, I will return to figure out what is going on.

**Comment by samapriya** [comment]
Thanks for the updates on your progress. I would also recommend using the cookie setup method mentioned here 

https://samapriya.github.io/geeup/projects/cookies_setup/

And then use --method cookies during upload

This bypasses the need for selenium based authentication since you are passing authenticated session cookies which it is then using to create an authenticated session during upload . This method also removes it's need for selenium and should work with both 2 factor and single sign on user accounts theoretically

**Comment by samapriya** [comment]
Since I haven't heard back in a bit, closing this for now, feel free to reopen, some minor improvements are upcoming in new release
