### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Lrogic** [samapriya/geeup#48]
I am trying to use the geeup upload command but I keep running into an issue after inputting my cookie:

`HTraceback (most recent call last):
  File "/usr/local/bin/geeup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/geeup/geeup.py", line 557, in main
    func(args)
  File "/usr/local/lib/python3.7/dist-packages/geeup/geeup.py", line 264, in upload_from_parser
    pyramiding=args.pyramids,
  File "/usr/local/lib/python3.7/dist-packages/geeup/batch_uploader.py", line 118, in upload
    google_session = __get_google_auth_session(user)
  File "/usr/local/lib/python3.7/dist-packages/geeup/batch_uploader.py", line 373, in __get_google_auth_session
    and ast.literal_eval(response.text)["url"] is not None
  File "/usr/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <!doctype html><html lang="en" dir="ltr"><head><base href="https://accounts.google.com/v3/signin/"><meta name="referrer" content="origin"><link rel="canonical" href="https://accounts.google.com/v3/signin/identifier"><meta name="viewport" content="width=device-width, initial-scale=1"><style data-href="https://www.gstatic.com/_/mss/boq-identity/_/ss/k=boq-identity.AccountsSignInUi.Odxar3sndLM.L.W.O/am=GAAFAAABAQAAAAAAAAAAABMh/d=1/ed=1/rs=AOaEmlEQ9jB2WTQ8ssU_5bFmfXV4_4IX8g/m=identifierview,_b,_tp,_r" nonce="krycMWWXfGStaLtyIWFp9A">c-wiz{contain:style}c-wiz>c-data{display:none}c-wiz.rETSD{contain:none}c-wiz.Ubi8Z{contain:layout style}.JnOM6e{background-color:transparent;border:none;-webkit-border-radius:4px;border-radius:4px;-webkit-box-sizing:border-box;box-sizing:border-box;display:inline-block;font-size:14px;height:36px;letter-spacing:.15px;line-height:34px;padding:0 24px;position:relative;text-align:center}.JnOM6e:focus-visible{outline:none;position:relative}.JnOM6e:focus-visible::after{border:2px solid #185abc;border-radius:6px;bottom:-4px;box-shadow:0 0 0 2px #e8f0fe;content:"";left:-4px;position:absolute;right:-4px;top:-4px}.rDisVe:focus:not(:focus-visible),.GjFdVe:focus:not(:focus-visible){box-shadow:0 1px 1px 0 rgba(66,133,244,.3),0 1px 3px 1px rgba(66,133,244,.15)}.rDisVe:hover:not(:focus-visible),.GjFdVe:hover:not(:focus-visible){box-shadow:0 1px 1px 0 rgba(66,133,244,.45),0 1px 3px 1px rgba(66,133,244,.3)}.JnOM6e:hover{cursor:pointer}.JnOM6e.kTeh9{line-height:36px;text-decoration:none}.JnOM6e.eLNT1d{display:none}.rDisVe{background-color:#1a73e8;color:#fff}.rDisVe:focus,.rDisVe:hover{background-color:#185abc}.GjFdVe{border:1px solid #dadce0;color:#1a73e8}.GjFdVe:active{background-color:#aecbfa;color:#174ea6}.GjFdVe:focus{background-color:#e8f0fe;border-color:#185abc;color:#174ea6}.GjFdVe:hover{background-color:#e8f0fe;color:#174ea6}.KXbQ4b{color:#1a73e8;min-width:0;padding-left:8px;padding-right:8px}.KXbQ4b:active,.KXbQ4b:hover{color:#185abc}.KXbQ4b:active{background-color:rgba(26,115,232,0.122)}.KXbQ4b:focus,.KXbQ4b:hover{background-color:rgba(26,115,232,0.039)}.aN1Vld{margin:16px 0;outline:none}.aN1Vld+.aN1Vld{margin-top:24px}.aN1Vld:first-child{margin-top:0}.aN1Vld:last-child{margin-bottom:0}.aN1Vld.uXELDc{-webkit-border-radius:8px;border-radius:8px;padding:16px}.aN1Vld.uXELDc>:first-child{margin-top:0}.aN1Vld.uXELDc>:last-child{margin-bottom:0}.aN1Vld.uXELDc .cySqRb{color:#202124}.aN1Vld.uXELDc .yOnVIb{color:#202124}.aN1Vld.uXELDc:not(.S7S4N)>.yOnVIb{margin-top:0}.aN1Vld.uXELDc.sj692e{background:#e8f0fe}.aN1Vld.uXELDc.Xq8bDe{background:#fce8e6}.aN1Vld.uXELDc.rNe0id{background:#fef7e0}.aN1Vld.uXELDc:not(.S7S4N){display:-webkit-box;display:-webkit-flex;display:flex}.aN1Vld.eLNT1d{display:none}.aN1Vld.SmR8{border:1px solid #dadce0;-webkit-border-radius:8px;border-radius:8px;padding:16px}.aN1Vld.SmR8 .EEiyWe{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-justify-content:flex-end;justify-content:flex-end;margin-top:16px}.aN1Vld.SmR8 .EEiyWe .GjFdVe{margin-bottom:0;margin-top:0}.wSQNd:empty{display:none}.wSQNd>:first-child{margin-top:0;padding-top:0}.wSQNd>:last-child{margin-bottom:0;padding-bottom:0}.cySqRb{-webkit-align-items:center;align-items:center;color:#202124;display:-webkit-box;display:-webkit-flex;display:flex;font-size:16px;font-weight:500;letter-spacing:0.1px;line-height:1.4286;margin-bottom:0;margin-top:0;padding:0}.zlrrr{color:#5f6368;-webkit-flex-shrink:0;flex-shrink:0;height:20px;margin-right:16px;width:20px}.zlrrr .GxLRef{height:100%;width:100%}.aN1Vld.uXELDc .zlrrr{margin-top:0}.aN1Vld.uXELDc.sj692e .zlrrr{color:#1967d2}.aN1Vld.uXELDc.Xq8bDe .zlrrr{color:#c5221f}.aN1Vld.uXELDc.rNe0id .zlrrr{color:#ea8600}.yOnVIb{margin:auto -24px;padding-left:24px;padding-right:24px;margin-bottom:16px;margin-top:10px}.aN1Vld.SmR8 .yOnVIb{margin-bottom:0;margin-top:16px}.yOnVIb>:first-child:not(section){margin-top:0;padding-top:0}.yOnVIb>:last-child:not(section){margin-bottom:0;padding-bottom:0}.wSQNd:empty+.yOnVIb{margin-top:0}.yOnVIb:only-child{margin-bottom:0;margin-top:0}*,*:before,*:after{-webkit-box-sizing:inherit;box-sizing:inherit}html{-webkit-box-sizing:border-box;box-sizing:border-box;-webkit-tap-highlight-color:transparent}body,input,textarea,select,button{color:#202124;font-family:arial,sans-serif}body{background:#fff;direction:ltr;display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;font-size:14px;line-height:1.4286;margin:0;min-height:100vh;padding:0;position:relative}@media all and (min-width:601px){body{-webkit-justify-content:center;justify-content:center}}[data-style="heading"],.BDEI9 h2:not(.TrZEUc){color:#202124;font-size:16px;font-weight:500;letter-spacing:0.1px;line-height:1.4286}.BDEI9 a{text-decoration:none}.BDEI9 a:not(.TrZEUc){-webkit-border-radius:4px;border-radius:4px;color:#1a73e8;display:inline-block;font-weight:500;letter-spacing:.25px;outline:0;position:relative;z-index:1}.BDEI9 button:not(.TrZEUc){-webkit-border-radius:4px;border-radius:4px;color:#1a73e8;display:inline-block;font-weight:500;letter-spacing:.25px;outline:0;position:relative;z-index:1;background-color:transparent;cursor:pointer;padding:0;text-align:left;border:0}.BDEI9 button::-moz-focus-inner{border:0}.BDEI9 a:not(.TrZEUc):focus::after,.BDEI9 a:not(.TrZEUc):active::after,.BDEI9 button:not(.TrZEUc):focus::after,.BDEI9 button:not(.TrZEUc):active::after{background-color:rgba(26,115,232,0.149);-webkit-border-radius:2px;border-radius:2px;bottom:-2px;content:"";left:-3px;position:absolute;right:-3px;top:-2px;z-index:-1}.BDEI9 img:not(.TrZEUc){border:0;max-height:1.3em;vertical-align:middle}@media all and (min-width:601px){.BDEI9{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;min-height:100vh;position:relative}.BDEI9:before,.BDEI9:after{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1;content:"";height:24px}.BDEI9:before{min-height:30px}.BDEI9:after{min-height:24px}.BDEI9.LZgQXe:after{min-height:63.9996px}}.gEc4r{display:-webkit-box;display:-webkit-flex;display:flex;height:24px;-webkit-justify-content:center;justify-content:center}.BrpTO{margin:auto;max-width:380px;overflow:hidden;position:relative}.BrpTO .Q8ElWe{position:relative;text-align:center}.viAgtf{-webkit-border-radius:50%;border-radius:50%;color:#5f6368;overflow:hidden}.eCirAf{line-height:1.4286}.cABCAe{width:100%}.cABCAe .viAgtf{-webkit-box-flex:none;-webkit-flex:none;flex:none;height:28px;margin-right:12px;width:28px}.cABCAe .Q8ElWe,.TPmpLe .Q8ElWe{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-align-items:center;align-items:center}.cABCAe .Q8ElWe{-webkit-justify-content:center;justify-content:center}.BrpTO .viAgtf{height:64px;margin:0 auto 8px;width:64px}.rs3gSb{-webkit-border-radius:50%;border-radius:50%;display:block}.cABCAe .rs3gSb,.cABCAe .hZUije,.cABCAe .kHluYc{max-height:100%;max-width:100%}.BrpTO .rs3gSb,.BrpTO .hZUije,.BrpTO .kHluYc{height:64px;width:64px}.TPmpLe{height:20px}.TPmpLe .viAgtf{margin-right:8px;height:20px;min-width:20px}.TPmpLe .rs3gSb,.TPmpLe .hZUije,.TPmpLe .kHluYc{color:#3c4043;height:20px;width:20px}.TPmpLe .kk39Eb{overflow:hidden}.TPmpLe .yavlK{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cABCAe .kk39Eb{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1}.cABCAe .eCirAf{color:#3c4043;font-size:14px;font-weight:500}.BrpTO .eCirAf{color:#202124;font-size:16px}.yavlK{direction:ltr;font-size:12px;text-align:left;line-height:1.3333;word-break:break-all}.FzDwd{direction:ltr;font-size:12px;text-align:left;line-height:1.3333;word-break:break-all;color:#5f6368}.TPmpLe .yavlK{color:#3c4043}.cABCAe .yavlK{color:#5f6368}.BrpTO .yavlK{color:#5f6368;text-align:center}.BtUzhd{color:#5f6368;font-size:12px}.cABCAe .BtUzhd{-webkit-align-self:flex-start;align-self:flex-start;-webkit-box-flex:none;-webkit-flex:none;flex:none;line-height:1.3333}.hZUije{border:0}.hZUije.WS4XDd{max-height:1.3333em;padding:0 2px;vertical-align:middle;width:auto}.kHluYc{border:0;object-fit:contain}.kHluYc.WS4XDd{max-height:1.3333em;padding:0 2px;vertical-align:middle;width:auto}.vOZun{padding-bottom:3px;padding-top:9px;margin-bottom:0;margin-top:0}.gomQac{padding-bottom:3px;padding-top:9px;margin:0}.vOZun:empty{display:none}.HUYFt{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;font-size:12px;-webkit-justify-content:space-between;justify-content:space-between;padding:0 24px 14px}.HUYFt .hXs2T,.HUYFt .M2nKge{line-height:48px}@media all and (min-width:601px){.HUYFt{padding-left:0;padding-right:0;position:absolute;width:100%}}.hXs2T .pUP0Nd{color:#5f6368}.hXs2T{margin-left:-16px;margin-right:16px}.N158t{-webkit-appearance:none;-webkit-appearance:none;appearance:none;background-color:transparent;background-image:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDI0IDI0IiB3aWR0aD0iMjRweCIgZmlsbD0iIzQ1NUE2NCI+PHBhdGggZD0iTTAgMGgyNHYyNEgwVjB6IiBmaWxsPSJub25lIi8+PHBhdGggZD0iTTcgMTBsNSA1IDUtNUg3eiIvPjwvc3ZnPg==");background-position:right;background-repeat:no-repeat;border:none;-webkit-border-radius:4px;border-radius:4px;color:#5f6368;cursor:pointer;font-size:12px;outline:none;padding:16.0002px 24px 16.0002px 16px;-webkit-transition:background;transition:background}.N158t:focus{background-color:#e8eaed}.M2nKge{list-style:none;margin:0 -16px;padding:0}.vomtoe{display:inline-block;margin:0}.pUP0Nd{-webkit-border-radius:4px;border-radius:4px;color:#5f6368;display:inline-block;outline:none;z-index:1}.pUP0Nd .UskCyf{background-color:transparent;padding:6px 16px;-webkit-transition:background;transition:background}.pUP0Nd:focus .UskCyf{background-color:#e8eaed;-webkit-border-radius:4px;border-radius:4px}.Ha17qf{background:#fff;display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-direction:column;flex-direction:column;max-width:100%;min-height:100vh;position:relative}@media all and (min-width:601px){.Ha17qf{background:#fff;border:1px solid #dadce0;-webkit-border-radius:8px;border-radius:8px;display:block;-webkit-flex-shrink:0;flex-shrink:0;margin:0 auto;min-height:0;width:450px}.Ha17qf.qmmlRd{width:450px}.Ha17qf.qmmlRd .Or16q{height:auto;min-height:500px}}.Or16q{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1;overflow:hidden;padding:24px 24px 36px}@media all and (min-width:601px){.Or16q{height:auto;min-height:500px;overflow-y:auto}}@media all and (min-width:450px){.Or16q{padding:48px 40px 36px}}.iEhbme{padding:24px 0 0}.iEhbme.RDPZE{opacity:.5;pointer-events:none}.HDuqac{background:transparent;border:none;color:#3c4043;cursor:pointer;display:-webkit-inline-box;display:-webkit-inline-flex;display:inline-flex;font-size:14px;letter-spacing:0.25px;max-width:100%}.BOs5fd{-webkit-align-items:center;align-items:center;background:#fff;border:1px solid #dadce0;display:-webkit-inline-box;display:-webkit-inline-flex;display:inline-flex;max-width:100%;position:relative}.HDuqac:focus-visible{outline:none}.HDuqac:focus-visible .BOs5fd{outline:none;position:relative;background:rgba(60,64,67,0.122)}.HDuqac:focus-visible .BOs5fd::after{border:2px solid #185abc;border-radius:20px;bottom:-5px;box-shadow:0 0 0 2px #e8f0fe;content:"";left:-5px;position:absolute;right:-5px;top:-5px}.HDuqac:focus:not(:focus-visible) .BOs5fd{box-shadow:0 1px 1px 0 rgba(66,133,244,.3),0 1px 3px 1px rgba(66,133,244,.15);border-color:#dadce0;-webkit-box-shadow:none;box-shadow:none}.HDuqac:hover:not(:focus-visible) .BOs5fd{background:rgba(60,64,67,0.039)}.HDuqac:focus .BOs5fd,.HDuqac:hover .BOs5fd{border-color:#dadce0}.HDuqac:active:focus .BOs5fd{background:rgba(60,64,67,0.122);border-color:#3c4043;color:#3c4043}.EI77qf{line-height:30px;margin:-8px 0;padding:8px 0}.EI77qf.DbQnIe{color:#1a73e8;font-size:12px;line-height:22px}.EI77qf .BOs5fd{-webkit-border-radius:16px;border-radius:16px;padding:0 15px 0 15px}.EI77qf.DbQnIe .BOs5fd{-webkit-border-radius:12px;border-radius:12px;padding:0 10px 0 10px}.EI77qf.iiFyne .BOs5fd{padding-right:7px}.EI77qf.cd29Sd .BOs5fd{padding-left:5px}.EI77qf.DbQnIe.cd29Sd .BOs5fd{padding-left:2px}.EI77qf.DbQnIe.iiFyne .BOs5fd{padding-right:7px}.hMeYtd{-webkit-border-radius:10px;border-radius:10px;height:20px;margin-right:8px}.hMeYtd .rs3gSb,.hMeYtd .hZUije,.hMeYtd .kHluYc{-webkit-border-radius:50%;border-radius:50%;color:#3c4043;display:block;height:20px;width:20px}.wJxLsd{direction:ltr;overflow:hidden;text-align:left;text-overflow:ellipsis;white-space:nowrap}.znpTjf{color:#3c4043;-webkit-flex-shrink:0;flex-shrink:0;height:18px;margin-left:4px;width:18px}.HDuqac.DbQnIe .znpTjf{height:16px;width:16px}.JC0zZc{display:block;height:100%;width:100%}.aMfydd{text-align:center}.aMfydd .Tn0LBd{padding-bottom:0;padding-top:16px;color:#202124;font-size:24px;font-weight:400;line-height:1.3333;margin-bottom:0;margin-top:0}.a2CQh{margin-bottom:0;margin-top:0;font-size:16px;font-weight:400;letter-spacing:0.1px;line-height:1.5;padding-bottom:0;padding-top:8px}.a2CQh:empty{display:none}.n868rf{display:-webkit-inline-box;display:-webkit-inline-flex;display:inline-flex;letter-spacing:.25px;min-height:24px;padding-bottom:0;padding-top:8px}.C7uRJc{margin-top:8px}.NveWz{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1}.i2knIc{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-box-flex:0;box-flex:0;-webkit-flex-grow:0;flex-grow:0;-webkit-flex-wrap:wrap;flex-wrap:wrap;margin-left:-8px;margin-top:32px;min-height:48px;padding-bottom:20px}.i2knIc.fXx9Lc{margin:0;min-height:0;padding:0}.sXlxWd{margin-bottom:32px;width:100%}.wg0fFb{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-direction:row-reverse;flex-direction:row-reverse;-webkit-flex-wrap:wrap;flex-wrap:wrap;width:100%}.RhTxBf,.tmMcIf{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1}.i2knIc.NNItQ:not(.F8PBrb) .RhTxBf,.i2knIc.NNItQ:not(.F8PBrb) .tmMcIf{text-align:center}.RhTxBf{text-align:right}.i2knIc.F8PBrb .wg0fFb{margin:0 -2px;margin-left:8px;width:-webkit-calc(100% + 4px);width:calc(100% + 4px)}.i2knIc.F8PBrb .RhTxBf{display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;width:100%}.i2knIc.F8PBrb .tmMcIf{margin:0 2px}.xOs3Jc{-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1;margin:0 2px;min-width:-webkit-calc(50% - 4px);min-width:calc(50% - 4px)}.Cokknd{margin-bottom:6px;margin-top:6px;white-space:nowrap;width:100%}.D4rY0b{color:#5f6368;font-size:14px;line-height:1.4286;margin-top:32px}.TRuRhd{margin-top:24px;position:relative}.Fu5aXd:first-child .TRuRhd{margin-top:8px}.xyezD{background-color:transparent;border:none;-webkit-box-sizing:border-box;box-sizing:border-box;color:#202124;font-size:16px;height:56px;outline:none;padding:0 14px;width:100%}.TRuRhd.YKooDc .xyezD{direction:ltr;text-align:left}.Yr2OOb{line-height:1.4286;margin:14px;padding:0;resize:vertical}.LBj8vb{background-color:transparent;border:none;font-size:16px;height:56px;padding:0 14px;outline:none;width:100%}.dXXNOd{display:-webkit-box;display:-webkit-flex;display:flex;width:100%}.xMpNCd:not(:empty){line-height:56px;padding-left:14px}.pkBWge:not(:empty){line-height:56px;padding-right:14px}.TRuRhd[data-has-domain-suffix] .pkBWge{display:-webkit-box;display:-webkit-flex;display:flex;white-space:nowrap}.TRuRhd[data-has-domain-suffix][data-has-at-sign] .pkBWge{display:none}.fjpXlc{display:-webkit-box;display:-webkit-flex;display:flex;height:100%}.nWPx2e{-webkit-align-items:stretch;align-items:stretch;display:-webkit-box;display:-webkit-flex;display:flex;-webkit-flex-direction:row;flex-direction:row;height:100%;-webkit-justify-content:flex-start;justify-content:flex-start;left:0;max-width:100%;pointer-events:none;position:absolute;top:0;width:100%}.YhhY8,.CCQ94b,.tNASEf{border:1px solid #dadce0}.YhhY8{border-bottom-left-radius:4px;border-right:none;border-top-left-radius:4px;width:8px}.CCQ94b{border-left:none;border-right:none;border-top:none;color:#5f6368;font-size:12px;margin:-6px 0 0;padding:0 6px}.tNASEf{border-bottom-right-radius:4px;border-left:none;border-top-right-radius:4px;-webkit-box-flex:1;box-flex:1;-webkit-flex-grow:1;flex-grow:1}.Fu5aXd:not(.Jj6Lae) .xyezD:focus+.nWPx2e .CCQ94b,.Fu5aXd:not(.Jj6Lae) .LBj8vb:focus+.nWPx2e .CCQ94b{color:#1a73e8}.xyezD:focus+.nWPx2e .YhhY8,.xyezD:focus+.nWPx2e .CCQ94b,.xyezD:focus+.nWPx2e .tNASEf,.LBj8vb:focus+.nWPx2e .YhhY8,.LBj8vb:focus+.nWPx2e .CCQ94b,.LBj8vb:focus+.nWPx2e .tNASEf{border-color:#1a73e8;border-width:2px}.F3wxlc{-webkit-align-items:flex-start;align-items:flex-start;color:#5f6368;display:-webkit-box;display:-webkit-flex;display:flex;font-size:12px;line-height:normal;margin-top:4px}.EllNBf{margin-right:8px;margin-top:-2px}.SnjiRb{height:16px;width:16px}.F3wxlc:empty,.NHVGlc:empty{display:none}.Fu5aXd.Jj6Lae .F3wxlc{color:#d93025}.Fu5aXd .azsAwf{margin-left:16px}.Fu5aXd.Jj6Lae .nWPx2e .YhhY8,.Fu5aXd.Jj6Lae .nWPx2e .CCQ94b,.Fu5aXd.Jj6Lae .nWPx2e .tNASEf{border-color:#d93025}.Fu5aXd.Jj6Lae .nWPx2e .CCQ94b{color:#d93025}.ZWssT{margin-top:26px}.vopC4e{background:transparent;border:none;-webkit-box-sizing:border-box;box-sizing:border-box;color:#202124;cursor:pointer;margin-bottom:-15px;margin-top:-15px;outline:inherit;padding-bottom:15px;padding-top:15px;position:relative;z-index:1}.vopC4e:focus::after{background-color:rgba(26,115,232,0.149);-webkit-border-radius:2px;border-radius:2px;bottom:0;content:"";left:0;position:absolute;right:0;top:0;z-index:-1}.JVMrYb{display:block}.hJIRO{display:none}.sQecwc{display:hidden}sentinel{}
    ^
SyntaxError: invalid syntax`

I saw previous issues had a similar error, but their cause was using an incognito browser. I am using chrome and I am not in incognito. Do you know what the cause might be? Thanks

**Comment by Lrogic** [comment]
Never mind, I found the issue was I didn't disable cannonical mode by using the "stty -icanon" command.
