### ISSUE TITLE
Issue of uploading shown in 

### ISSUE THREAD

**Issue by JustinWenzhaoLi** [samapriya/geeup#54]
Hi, 

I tried:
(base) C:\Users\wenzh>geeup upload --source F:/evspsbl_Amon_ACCESS-CM2_ssp245 --dest users/[my username]/evspsbl_Amon_ACCESS-CM2_ssp245 -u [my email] -m F:/evspsbl_Amon_ACCESS-CM2_ssp245_r1i1p1f1_LUT.csv

but come back with:

Traceback (most recent call last):
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\_cloud_api_utils.py", line 160, in build_cloud_resource
    resource = build(static_discovery=False)
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\_cloud_api_utils.py", line 145, in build
    return discovery.build(
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
TypeError: build() got an unexpected keyword argument 'static_discovery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wenzh\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wenzh\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\wenzh\Anaconda3\Scripts\geeup.exe\__main__.py", line 7, in <module>
  File "c:\users\wenzh\anaconda3\lib\site-packages\geeup\geeup.py", line 654, in main
    func(args)
  File "c:\users\wenzh\anaconda3\lib\site-packages\geeup\geeup.py", line 300, in upload_from_parser
    upload(
  File "c:\users\wenzh\anaconda3\lib\site-packages\geeup\batch_uploader.py", line 103, in upload
    ee.Initialize()
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\__init__.py", line 116, in Initialize
    data.initialize(
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\data.py", line 199, in initialize
    _install_cloud_api_resource()
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\data.py", line 266, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\_cloud_api_utils.py", line 162, in build_cloud_resource
    resource = build()
  File "c:\users\wenzh\anaconda3\lib\site-packages\ee\_cloud_api_utils.py", line 145, in build
    return discovery.build(
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\discovery.py", line 270, in build
    content = _retrieve_discovery_doc(
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\discovery.py", line 376, in _retrieve_discovery_doc
    resp, content = req.execute(num_retries=num_retries)
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\http.py", line 900, in execute
    resp, content = _retry_request(
  File "c:\users\wenzh\anaconda3\lib\site-packages\googleapiclient\http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "c:\users\wenzh\anaconda3\lib\site-packages\google_auth_httplib2.py", line 189, in request
    self.credentials.before_request(
  File "c:\users\wenzh\anaconda3\lib\site-packages\google\auth\credentials.py", line 133, in before_request
    self.refresh(request)
  File "c:\users\wenzh\anaconda3\lib\site-packages\google\oauth2\credentials.py", line 200, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "c:\users\wenzh\anaconda3\lib\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "c:\users\wenzh\anaconda3\lib\site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "c:\users\wenzh\anaconda3\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')

It seems the Token is not accepted. 
I have done the pasting of geeup cookie_setup

Could you help me with this issue?

**Comment by JustinWenzhaoLi** [comment]
This has been solved by using the command:
earthengine authenticate -- auth_mode=notebook

**Comment by zicai1** [comment]
take away '=',```earthengine authenticate --auth_mode notebook```
