### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sermomon** [samapriya/geeup#58]
I'm trying to upload an image using Anaconda Python.

My GeoTiff image is located in the following local directory: `C:/assets/img/020201_2021CVAL0025_25830_8bits_RGBI_0519_4-8_1M.tif`
My metadata file is located in the following local directory: `C:/assets/meta.csv`

I'm using the following code from Jupyter Notebook:

```
import ee
ee.Initialize()

!geeup quota
```
This returns the following:

```
Root assets path: users/sermomon
Used 12.62 GB of 250 GB
Used 14 assets of 50,000 total
```

Since here we can check that my account is correctly  initialized. Then, I try tu upload the image:

`!geeup upload --source C:/assets/img --dest users/sermomon/test_geeup -u sermomon.gee@gmail.com -m C:/assets/meta.csv`

I obtain the following error:

```
Traceback (most recent call last):
  File "C:\Users\sergi\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sergi\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sergi\anaconda3\Scripts\geeup.exe\__main__.py", line 7, in <module>
  File "C:\Users\sergi\anaconda3\lib\site-packages\geeup\geeup.py", line 822, in main
    func(args)
  File "C:\Users\sergi\anaconda3\lib\site-packages\geeup\geeup.py", line 593, in upload_from_parser
    upload(
  File "C:\Users\sergi\anaconda3\lib\site-packages\geeup\batch_uploader.py", line 105, in upload
    google_session = __get_google_auth_session(user)
  File "C:\Users\sergi\anaconda3\lib\site-packages\geeup\batch_uploader.py", line 329, in __get_google_auth_session
    cookie_list = json.load(json_file)
  File "C:\Users\sergi\anaconda3\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\sergi\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\sergi\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\sergi\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by e5k** [comment]
@sermomon did you get a fix for this?

**Comment by aazuspan** [comment]
This can happen if there's an error while writing the cookie list that leaves behind an empty, unparseable JSON file. 

https://github.com/samapriya/geeup/blob/5c2a1e99cfca3c35b39d3ebfdc0c7f2bd7d66797/geeup/batch_uploader.py#L324-L325

Running `geeup cookie_setup` and re-entering the cookie list should replace the corrupted file.
