### ISSUE TITLE
WARNING Encountered 403 Forbidden with reason "PERMISSION_DENIED"

### ISSUE THREAD

**Issue by diegomanya** [samapriya/geeup#59]
Hi, hope you have a nice christmas. I've using geeup for a while to upload assets (~5k) without problem. Until today in which I notice that the ee.Initialize is no longer using the pasted token but getting authenticated through collab. See [here](https://developers.google.com/earth-engine/guides/auth).
Unfortunately this seems to be causing an issue with geeup since all function that worked before fail now with the message
`2023-12-20 04:49:37 WARNING No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable
2023-12-20 04:49:38 WARNING Encountered 403 Forbidden with reason "PERMISSION_DENIED"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ee/data.py", line 383, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://earthengine.googleapis.com/v1/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json returned "Google Earth Engine API has not been used in project 522309567947 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/earthengine.googleapis.com/overview?project=522309567947 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console API activation', 'url': 'https://console.developers.google.com/apis/api/earthengine.googleapis.com/overview?project=522309567947'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'SERVICE_DISABLED', 'domain': 'googleapis.com', 'metadata': {'service': 'earthengine.googleapis.com', 'consumer': 'projects/522309567947'}}]">
`
Any suggestions to address this issue if possible? Thanks a lot

**Comment by yin00406** [comment]
I encountered the same problem. It looks like some part of this code need to be updated

**Comment by yin00406** [comment]
Previously, I used colab with geeup and encountered this problem. After I change to local environment, my problem is solved.

**Comment by samapriya** [comment]
I am not sure what the issue was here but this is being fixed in v2.0.0 I didn't really design this for use in colab but I can keep that in mind
